[tools]
rust = "1.74.1"
doctl = "1.65.0"
duf = "0.8.1"
fd = "8.4.0"
golang = "1.22.4"
helm = "3.11.0"
httpie-go = "0.7.0"
k3d = "5.6.3"
k9s = "0.32.4"
kubectl = "1.22.2"
kubeseal = "0.16.0"
nodejs = "22.5.1"
pulumi = "3.16.0"
python = "3.12.3"
sops = "3.7.3"
terraform = "1.5.6"
tilt = "0.30.4"
awscli = "2.17.33"
ansible-base = "2.10.17"
helmfile = "0.144.0"
argocd = "2.4.14"
pluto = "5.10.2"
github-cli = "2.66.1"
terraform-docs = "0.16.0"
kustomize = "4.5.7"
tflint = "0.43.0"
golangci-lint = "1.50.1"
kubent = "0.6.0"
flux2 = "0.37.0"
dyff = "1.5.6"
terragrunt = "0.42.7"
tfupdate = "0.6.7"
yq = "4.40.3"
istioctl = "1.19.10"
java = "openjdk-21.0.2"
steampipe = "0.21.7"
k6 = "0.49.0"
stern = "1.28.0"
helm-diff = "3.6.0"
pandoc = "3.2"
yamllint = "1.35.1"
gcloud = "latest"
vcluster = "latest"
fzf = "0.55.0"
gh = "2.66.1"
