return {
  "williamboman/mason.nvim",
  version = "^1.0.0",
  opts = {
    ensure_installed = {
      "gopls",
      "goimports",
      "pyright",
      "ruff",
      "ansible-lint",
      "actionlint",
      "ansible-language-server",
      "bash-language-server",
      "debugpy",
      "delve",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "gofumpt",
      "hadolint",
      "helm-ls",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "shellcheck",
      "shfmt",
      "stylua",
      "taplo",
      "terraform-ls",
      "tflint",
      "yaml-language-server",
      "yamlfmt",
    },
  },
}
